"""Publication state model and PRODUCT2 gate constants."""

from __future__ import annotations

from typing import Literal

# Explicit publication states — no implicit progression.
STATE_INTERNAL_FULL = "INTERNAL_FULL"
STATE_NONCOMMERCIAL_COMPLIANT = "NONCOMMERCIAL_DISTRIBUTION_COMPLIANT"
STATE_PUBLICATION_CANDIDATE = "PUBLICATION_CANDIDATE"
STATE_PUBLICATION_READY = "PUBLICATION_READY"
STATE_PUBLICATION_AUTHORIZED = "PUBLICATION_AUTHORIZED"
STATE_PUBLISHED = "PUBLISHED"

PublicationState = Literal[
    "INTERNAL_FULL",
    "NONCOMMERCIAL_DISTRIBUTION_COMPLIANT",
    "PUBLICATION_CANDIDATE",
    "PUBLICATION_READY",
    "PUBLICATION_AUTHORIZED",
    "PUBLISHED",
]

PRODUCT_PROFILE_NONCOMMERCIAL = "NONCOMMERCIAL_DISTRIBUTION"

DECISION_READY = "PRODUCT2_PUBLICATION_READINESS_READY"
DECISION_BLOCKED = "PRODUCT2_PUBLICATION_READINESS_BLOCKED"

GATE_PASS = "PASS"
GATE_BLOCK = "BLOCK"
GATE_AWAITING_HUMAN_AUTHORIZATION = "AWAITING_HUMAN_AUTHORIZATION"

REGRESSION_PASS = "PASS"
REGRESSION_EXPECTED_OWNER_RIGHTS_EXCLUSION = "EXPECTED_OWNER_RIGHTS_EXCLUSION"
REGRESSION_UNEXPECTED_PUBLICATION_CANDIDATE_DEFECT = "UNEXPECTED_PUBLICATION_CANDIDATE_DEFECT"

# PRODUCT2 may reach PUBLICATION_READY; must not set AUTHORIZED or PUBLISHED.
PRODUCT2_ALLOWED_TARGET_STATES = frozenset(
    {STATE_PUBLICATION_CANDIDATE, STATE_PUBLICATION_READY}
)
