"""Distribution rights states and artifact classification."""

from __future__ import annotations

from typing import Literal

PROFILE_INTERNAL_FULL = "INTERNAL_FULL"
PROFILE_NONCOMMERCIAL_CANDIDATE = "NONCOMMERCIAL_DISTRIBUTION_CANDIDATE"

DECISION_READY = "PRODUCT1B_NONCOMMERCIAL_DISTRIBUTION_COMPLIANCE_READY"
DECISION_BLOCKED = "PRODUCT1B_NONCOMMERCIAL_DISTRIBUTION_COMPLIANCE_BLOCKED"

DistributionState = Literal[
    "NONCOMMERCIAL_DISTRIBUTION_ALLOWED",
    "NONCOMMERCIAL_DISTRIBUTION_ALLOWED_WITH_ATTRIBUTION",
    "NONCOMMERCIAL_DISTRIBUTION_ALLOWED_SHAREALIKE",
    "INTERNAL_ONLY",
    "DISTRIBUTION_PERMISSION_NOT_RECORDED",
    "REQUIRES_RIGHTS_REVIEW",
    "UNKNOWN",
    "BLOCKED_DISTRIBUTION",
]

ArtifactRightsClass = Literal[
    "MALIDABA_ADAPTED_DATA",
    "COLLECTION_METADATA",
    "SOFTWARE_CODE",
    "OTHER_SOURCE_DATA",
    "MIXED_DATA_COLLECTION",
]

ExclusionReason = Literal[
    "INTERNAL_ONLY",
    "DISTRIBUTION_PERMISSION_NOT_RECORDED",
    "UNKNOWN",
    "OTHER_RIGHTS_BLOCK",
]

CHECK_PASS = "PASS"
CHECK_BLOCK = "BLOCK"

SOFTWARE_LICENSE = "MIT OR Apache-2.0"
DATA_LICENSE_POLICY = "source_specific"
