export type SearchDirection = "source_to_target" | "target_to_source";

export type SessionType = "structured_usability" | "developer_smoke" | "natural_use";

export type IssueClass =
  | "no_issue_observed"
  | "phrase_mismatch"
  | "missing_entry"
  | "index_gap"
  | "language_mismatch"
  | "spelling_error"
  | "setup_ux"
  | "interpretability"
  | "probe_or_test"
  | "pending_human_review";

export type CandidateInterventionCategory =
  | "none"
  | "source_aliases"
  | "source_index_supplements"
  | "result_interpretability"
  | "phrase_handling"
  | "product_copy_onboarding"
  | "offline_install_reliability"
  | "human_review_required";

export type DiagnosticPersona = {
  id: string;
  location: "Guinea" | "North America";
  userType: string;
  whyThisPersonMatters: string;
  primaryQuestion: string;
  deviceCondition: string;
  tasks: ScenarioTask[];
};

export type ScenarioTask = {
  id: string;
  layer: "scenario_card" | "moderator_probe" | "offline_check";
  prompt: string;
  query: string;
  intention: string;
  direction: SearchDirection;
  retryQuery?: string;
  retryReason?: string;
  expectedIssueClass: IssueClass;
  candidateInterventionCategory: CandidateInterventionCategory;
  userImpact: string;
};

const sharedScenarioPrompts = {
  family: "Find a word about family.",
  dailyLife: "Find a word about food, the market, or daily life.",
  health: "Find a word about the body, health, or care.",
  reverse: "Search for a Maninka word you already know.",
  phrase: "Search for a short phrase you might naturally say.",
  offline: "Turn off internet, reopen the app, and search again.",
} as const;

export const diagnosticPersonas: DiagnosticPersona[] = [
  {
    id: "G1",
    location: "Guinea",
    userType: "Secondary-school or university student",
    whyThisPersonMatters: "French-heavy school vocabulary, abstract terms, and spelling variants.",
    primaryQuestion: "Can the app support French-to-Maninka learning without technical knowledge?",
    deviceCondition: "Desktop Chromium proxy for school-device flow; scripted rows are not demand evidence.",
    tasks: [
      {
        id: "G1-family",
        layer: "scenario_card",
        prompt: sharedScenarioPrompts.family,
        query: "frère",
        intention: "Find a real family relationship term from French.",
        direction: "source_to_target",
        expectedIssueClass: "pending_human_review",
        candidateInterventionCategory: "human_review_required",
        userImpact: "Kinship ambiguity may make a broad hit hard to trust.",
      },
      {
        id: "G1-school",
        layer: "scenario_card",
        prompt: sharedScenarioPrompts.dailyLife,
        query: "devoir",
        intention: "Look up school vocabulary likely used in coursework.",
        direction: "source_to_target",
        expectedIssueClass: "pending_human_review",
        candidateInterventionCategory: "human_review_required",
        userImpact: "A miss or unclear result blocks school-oriented learning use.",
      },
      {
        id: "G1-health",
        layer: "scenario_card",
        prompt: sharedScenarioPrompts.health,
        query: "tête",
        intention: "Find a body-related French term.",
        direction: "source_to_target",
        expectedIssueClass: "pending_human_review",
        candidateInterventionCategory: "human_review_required",
        userImpact: "Health vocabulary needs clear misses and understandable hits.",
      },
      {
        id: "G1-reverse",
        layer: "scenario_card",
        prompt: sharedScenarioPrompts.reverse,
        query: "Kùn",
        intention: "Try a remembered Maninka body word with tone mark.",
        direction: "target_to_source",
        retryQuery: "Kun",
        retryReason: "Check whether the user can recover after omitting accents.",
        expectedIssueClass: "spelling_error",
        candidateInterventionCategory: "source_aliases",
        userImpact: "Accent sensitivity can block fast phone-style lookup.",
      },
      {
        id: "G1-phrase",
        layer: "scenario_card",
        prompt: sharedScenarioPrompts.phrase,
        query: "comment dit-on école",
        intention: "Ask a phrase-like learning question rather than a lemma.",
        direction: "source_to_target",
        expectedIssueClass: "phrase_mismatch",
        candidateInterventionCategory: "phrase_handling",
        userImpact: "The app must communicate dictionary lookup instead of sentence translation.",
      },
      {
        id: "G1-offline",
        layer: "offline_check",
        prompt: sharedScenarioPrompts.offline,
        query: "école",
        intention: "Confirm a school query still works after offline reopen.",
        direction: "source_to_target",
        expectedIssueClass: "setup_ux",
        candidateInterventionCategory: "offline_install_reliability",
        userImpact: "Offline failure would break use in low-connectivity settings.",
      },
    ],
  },
  {
    id: "G2",
    location: "Guinea",
    userType: "Market trader / small-business operator",
    whyThisPersonMatters: "Everyday transactional vocabulary, intermittent connectivity, low setup patience.",
    primaryQuestion: "Does the app remain useful when a quick answer is needed?",
    deviceCondition: "Desktop Chromium proxy for low-patience market flow.",
    tasks: [
      {
        id: "G2-family",
        layer: "scenario_card",
        prompt: sharedScenarioPrompts.family,
        query: "femme",
        intention: "Find a family or household relationship word.",
        direction: "source_to_target",
        expectedIssueClass: "pending_human_review",
        candidateInterventionCategory: "human_review_required",
        userImpact: "Ambiguous relationship terms need review before action.",
      },
      {
        id: "G2-market",
        layer: "scenario_card",
        prompt: sharedScenarioPrompts.dailyLife,
        query: "prix",
        intention: "Look up a market transaction concept.",
        direction: "source_to_target",
        retryQuery: "argent",
        retryReason: "Try a related market term after a possible miss.",
        expectedIssueClass: "pending_human_review",
        candidateInterventionCategory: "human_review_required",
        userImpact: "Market misses reduce practical everyday value.",
      },
      {
        id: "G2-health",
        layer: "scenario_card",
        prompt: sharedScenarioPrompts.health,
        query: "fatigué",
        intention: "Find a common health/state word.",
        direction: "source_to_target",
        expectedIssueClass: "pending_human_review",
        candidateInterventionCategory: "human_review_required",
        userImpact: "Everyday care terms need clear feedback.",
      },
      {
        id: "G2-reverse",
        layer: "scenario_card",
        prompt: sharedScenarioPrompts.reverse,
        query: "Sen",
        intention: "Try a remembered Maninka form without diacritics.",
        direction: "target_to_source",
        expectedIssueClass: "spelling_error",
        candidateInterventionCategory: "source_aliases",
        userImpact: "Unaccented lookup may be the normal phone input path.",
      },
      {
        id: "G2-phrase",
        layer: "scenario_card",
        prompt: sharedScenarioPrompts.phrase,
        query: "combien ça coûte",
        intention: "Search a market phrase the user might say aloud.",
        direction: "source_to_target",
        expectedIssueClass: "phrase_mismatch",
        candidateInterventionCategory: "phrase_handling",
        userImpact: "Phrase expectations are likely in practical transaction use.",
      },
      {
        id: "G2-offline",
        layer: "offline_check",
        prompt: sharedScenarioPrompts.offline,
        query: "riz",
        intention: "Check offline reopen for a food/market term.",
        direction: "source_to_target",
        expectedIssueClass: "setup_ux",
        candidateInterventionCategory: "offline_install_reliability",
        userImpact: "Offline persistence is central for intermittent connectivity.",
      },
    ],
  },
  {
    id: "G3",
    location: "Guinea",
    userType: "Parent or caregiver",
    whyThisPersonMatters: "Health, family, food, household, child-related searches and phrase-like needs.",
    primaryQuestion: "Do users try sentence-like needs where the product is lemma-oriented?",
    deviceCondition: "Desktop Chromium proxy for caregiver flow.",
    tasks: [
      {
        id: "G3-family",
        layer: "scenario_card",
        prompt: sharedScenarioPrompts.family,
        query: "enfant",
        intention: "Find child-related family vocabulary.",
        direction: "source_to_target",
        expectedIssueClass: "pending_human_review",
        candidateInterventionCategory: "human_review_required",
        userImpact: "Caregiver vocabulary is high-impact but needs meaning review.",
      },
      {
        id: "G3-food",
        layer: "scenario_card",
        prompt: sharedScenarioPrompts.dailyLife,
        query: "eau",
        intention: "Look up a basic household need.",
        direction: "source_to_target",
        expectedIssueClass: "pending_human_review",
        candidateInterventionCategory: "human_review_required",
        userImpact: "Basic household misses are highly visible.",
      },
      {
        id: "G3-health",
        layer: "scenario_card",
        prompt: sharedScenarioPrompts.health,
        query: "fièvre",
        intention: "Search a child-health term.",
        direction: "source_to_target",
        retryQuery: "malade",
        retryReason: "Try a broader care word after a possible miss.",
        expectedIssueClass: "pending_human_review",
        candidateInterventionCategory: "human_review_required",
        userImpact: "Care-related misses may cause users to abandon the app.",
      },
      {
        id: "G3-reverse",
        layer: "scenario_card",
        prompt: sharedScenarioPrompts.reverse,
        query: "kùn",
        intention: "Reverse lookup a remembered Maninka body word.",
        direction: "target_to_source",
        expectedIssueClass: "pending_human_review",
        candidateInterventionCategory: "human_review_required",
        userImpact: "Correct Maninka interpretation is left for owner review.",
      },
      {
        id: "G3-phrase",
        layer: "scenario_card",
        prompt: sharedScenarioPrompts.phrase,
        query: "mon enfant est malade",
        intention: "Try a caregiver phrase instead of a dictionary lemma.",
        direction: "source_to_target",
        expectedIssueClass: "phrase_mismatch",
        candidateInterventionCategory: "phrase_handling",
        userImpact: "A safe phrase miss can be acceptable if guidance is clear.",
      },
      {
        id: "G3-offline",
        layer: "offline_check",
        prompt: sharedScenarioPrompts.offline,
        query: "manger",
        intention: "Check offline household lookup after reopen.",
        direction: "source_to_target",
        expectedIssueClass: "setup_ux",
        candidateInterventionCategory: "offline_install_reliability",
        userImpact: "Caregiver use should not depend on live connectivity.",
      },
    ],
  },
  {
    id: "G4",
    location: "Guinea",
    userType: "Teacher, tutor, literacy worker, or community mediator",
    whyThisPersonMatters: "Repeated explanatory use and result interpretability for learners.",
    primaryQuestion: "Can an intermediary explain the app without teaching internals?",
    deviceCondition: "Desktop Chromium proxy for teaching/mediation flow.",
    tasks: [
      {
        id: "G4-family",
        layer: "scenario_card",
        prompt: sharedScenarioPrompts.family,
        query: "famille",
        intention: "Look up a broad family concept.",
        direction: "source_to_target",
        expectedIssueClass: "interpretability",
        candidateInterventionCategory: "result_interpretability",
        userImpact: "Broad terms may produce results that require learner-friendly explanation.",
      },
      {
        id: "G4-school",
        layer: "scenario_card",
        prompt: sharedScenarioPrompts.dailyLife,
        query: "livre",
        intention: "Find a literacy-related classroom word.",
        direction: "source_to_target",
        expectedIssueClass: "pending_human_review",
        candidateInterventionCategory: "human_review_required",
        userImpact: "Teacher use depends on confidence in result meaning.",
      },
      {
        id: "G4-health",
        layer: "scenario_card",
        prompt: sharedScenarioPrompts.health,
        query: "main",
        intention: "Search a body word that may be common in lessons.",
        direction: "source_to_target",
        expectedIssueClass: "pending_human_review",
        candidateInterventionCategory: "human_review_required",
        userImpact: "Common body-word hits should be easy to interpret.",
      },
      {
        id: "G4-reverse",
        layer: "scenario_card",
        prompt: sharedScenarioPrompts.reverse,
        query: "kùn",
        intention: "Moderator-only decomposed Unicode normalization check.",
        direction: "target_to_source",
        expectedIssueClass: "probe_or_test",
        candidateInterventionCategory: "none",
        userImpact: "NFC/NFD equivalence is correctness evidence, not demand.",
      },
      {
        id: "G4-phrase",
        layer: "scenario_card",
        prompt: sharedScenarioPrompts.phrase,
        query: "je veux apprendre le maninka",
        intention: "Try a learner phrase that may reveal expectation mismatch.",
        direction: "source_to_target",
        expectedIssueClass: "phrase_mismatch",
        candidateInterventionCategory: "product_copy_onboarding",
        userImpact: "Clear copy can prevent users from expecting free translation.",
      },
      {
        id: "G4-offline",
        layer: "offline_check",
        prompt: sharedScenarioPrompts.offline,
        query: "écrire",
        intention: "Check offline persistence for literacy vocabulary.",
        direction: "source_to_target",
        expectedIssueClass: "setup_ux",
        candidateInterventionCategory: "offline_install_reliability",
        userImpact: "Teaching use may occur where connectivity is unstable.",
      },
    ],
  },
  {
    id: "G5",
    location: "Guinea",
    userType: "Bilingual youth / phone-native user",
    whyThisPersonMatters: "Fast typing, informal spelling, accent omission, code-switching, retries.",
    primaryQuestion: "Where does phone typing diverge from clean normalized forms?",
    deviceCondition: "Desktop Chromium proxy with typed retries and accent omission.",
    tasks: [
      {
        id: "G5-family",
        layer: "scenario_card",
        prompt: sharedScenarioPrompts.family,
        query: "papa",
        intention: "Use informal family vocabulary instead of formal French.",
        direction: "source_to_target",
        retryQuery: "père",
        retryReason: "Try a formal equivalent after informal input.",
        expectedIssueClass: "missing_entry",
        candidateInterventionCategory: "source_aliases",
        userImpact: "Informal/common forms may need onboarding or aliases after review.",
      },
      {
        id: "G5-phone",
        layer: "scenario_card",
        prompt: sharedScenarioPrompts.dailyLife,
        query: "telephone",
        intention: "Search without accent while typing quickly.",
        direction: "source_to_target",
        expectedIssueClass: "spelling_error",
        candidateInterventionCategory: "source_aliases",
        userImpact: "Accent omission is likely in real phone input.",
      },
      {
        id: "G5-health",
        layer: "scenario_card",
        prompt: sharedScenarioPrompts.health,
        query: "ventre",
        intention: "Find a common body word.",
        direction: "source_to_target",
        expectedIssueClass: "pending_human_review",
        candidateInterventionCategory: "human_review_required",
        userImpact: "Fast lookup still needs semantically correct results.",
      },
      {
        id: "G5-reverse",
        layer: "scenario_card",
        prompt: sharedScenarioPrompts.reverse,
        query: "Kun",
        intention: "Reverse lookup an unaccented remembered Maninka form.",
        direction: "target_to_source",
        retryQuery: "Kùn",
        retryReason: "Retry with tone mark after an unaccented attempt.",
        expectedIssueClass: "spelling_error",
        candidateInterventionCategory: "source_aliases",
        userImpact: "Retry behavior reveals whether spelling support is worth considering.",
      },
      {
        id: "G5-phrase",
        layer: "scenario_card",
        prompt: sharedScenarioPrompts.phrase,
        query: "merci beaucoup",
        intention: "Try a high-probability social phrase.",
        direction: "source_to_target",
        expectedIssueClass: "phrase_mismatch",
        candidateInterventionCategory: "phrase_handling",
        userImpact: "Common phrases may reveal expectation mismatch.",
      },
      {
        id: "G5-offline",
        layer: "offline_check",
        prompt: sharedScenarioPrompts.offline,
        query: "moto",
        intention: "Check offline lookup for daily transport vocabulary.",
        direction: "source_to_target",
        expectedIssueClass: "setup_ux",
        candidateInterventionCategory: "offline_install_reliability",
        userImpact: "Phone-native users may expect instant offline reopening.",
      },
    ],
  },
  {
    id: "N1",
    location: "North America",
    userType: "Diaspora parent teaching children Maninka",
    whyThisPersonMatters: "Heritage-language vocabulary, kinship, household words, child-directed phrases.",
    primaryQuestion: "Can the app support language transmission at home?",
    deviceCondition: "Desktop Chromium proxy for home teaching flow.",
    tasks: [
      {
        id: "N1-family",
        layer: "scenario_card",
        prompt: sharedScenarioPrompts.family,
        query: "maman",
        intention: "Search child-directed family vocabulary.",
        direction: "source_to_target",
        retryQuery: "mère",
        retryReason: "Retry with formal French after household speech.",
        expectedIssueClass: "missing_entry",
        candidateInterventionCategory: "source_aliases",
        userImpact: "Home teaching often starts with familiar, informal words.",
      },
      {
        id: "N1-food",
        layer: "scenario_card",
        prompt: sharedScenarioPrompts.dailyLife,
        query: "dormir",
        intention: "Look up a child-directed household verb.",
        direction: "source_to_target",
        expectedIssueClass: "pending_human_review",
        candidateInterventionCategory: "human_review_required",
        userImpact: "Verb coverage and sense clarity need human review.",
      },
      {
        id: "N1-health",
        layer: "scenario_card",
        prompt: sharedScenarioPrompts.health,
        query: "bébé",
        intention: "Search a care-related family word.",
        direction: "source_to_target",
        expectedIssueClass: "pending_human_review",
        candidateInterventionCategory: "human_review_required",
        userImpact: "Child-directed vocabulary needs careful disposition.",
      },
      {
        id: "N1-reverse",
        layer: "scenario_card",
        prompt: sharedScenarioPrompts.reverse,
        query: "ba",
        intention: "Try a remembered short Maninka-like family form.",
        direction: "target_to_source",
        expectedIssueClass: "pending_human_review",
        candidateInterventionCategory: "human_review_required",
        userImpact: "Short remembered forms can be ambiguous and need owner judgment.",
      },
      {
        id: "N1-phrase",
        layer: "scenario_card",
        prompt: sharedScenarioPrompts.phrase,
        query: "viens ici",
        intention: "Try a household phrase used with children.",
        direction: "source_to_target",
        expectedIssueClass: "phrase_mismatch",
        candidateInterventionCategory: "phrase_handling",
        userImpact: "Home teaching may expose phrase expectations quickly.",
      },
      {
        id: "N1-offline",
        layer: "offline_check",
        prompt: sharedScenarioPrompts.offline,
        query: "eau",
        intention: "Check offline persistence for household vocabulary.",
        direction: "source_to_target",
        expectedIssueClass: "setup_ux",
        candidateInterventionCategory: "offline_install_reliability",
        userImpact: "Parents should not need technical recovery steps after install.",
      },
    ],
  },
  {
    id: "N2",
    location: "North America",
    userType: "Young adult heritage learner",
    whyThisPersonMatters: "Reverse lookup from remembered sounds and spelling uncertainty.",
    primaryQuestion: "Does the app help when sound is remembered before spelling?",
    deviceCondition: "Desktop Chromium proxy for uncertain reverse lookup.",
    tasks: [
      {
        id: "N2-family",
        layer: "scenario_card",
        prompt: sharedScenarioPrompts.family,
        query: "grand-mère",
        intention: "Search French kinship vocabulary remembered from family context.",
        direction: "source_to_target",
        expectedIssueClass: "pending_human_review",
        candidateInterventionCategory: "human_review_required",
        userImpact: "Kinship semantics require careful human disposition.",
      },
      {
        id: "N2-food",
        layer: "scenario_card",
        prompt: sharedScenarioPrompts.dailyLife,
        query: "arachide",
        intention: "Look up a food word likely heard at home.",
        direction: "source_to_target",
        expectedIssueClass: "pending_human_review",
        candidateInterventionCategory: "human_review_required",
        userImpact: "Heritage learners may use household food as entry point.",
      },
      {
        id: "N2-health",
        layer: "scenario_card",
        prompt: sharedScenarioPrompts.health,
        query: "dent",
        intention: "Find a body word from French.",
        direction: "source_to_target",
        expectedIssueClass: "pending_human_review",
        candidateInterventionCategory: "human_review_required",
        userImpact: "Simple body vocabulary should have clear feedback.",
      },
      {
        id: "N2-reverse",
        layer: "scenario_card",
        prompt: sharedScenarioPrompts.reverse,
        query: "sɛn",
        intention: "Try a phonetic remembered Maninka-like spelling.",
        direction: "target_to_source",
        retryQuery: "Sen",
        retryReason: "Retry with plain Latin spelling after phonetic input.",
        expectedIssueClass: "spelling_error",
        candidateInterventionCategory: "source_aliases",
        userImpact: "Pronunciation-memory input may need future spelling support.",
      },
      {
        id: "N2-phrase",
        layer: "scenario_card",
        prompt: sharedScenarioPrompts.phrase,
        query: "what does kun mean",
        intention: "Code-switch with English while asking about a remembered word.",
        direction: "target_to_source",
        expectedIssueClass: "language_mismatch",
        candidateInterventionCategory: "product_copy_onboarding",
        userImpact: "Mixed-language input reveals mental model mismatch.",
      },
      {
        id: "N2-offline",
        layer: "offline_check",
        prompt: sharedScenarioPrompts.offline,
        query: "Kùn",
        intention: "Check offline reverse lookup after reopen.",
        direction: "target_to_source",
        expectedIssueClass: "setup_ux",
        candidateInterventionCategory: "offline_install_reliability",
        userImpact: "Offline persistence matters for repeated heritage learning.",
      },
    ],
  },
  {
    id: "N3",
    location: "North America",
    userType: "Adult learner with French background",
    whyThisPersonMatters: "French-to-Maninka learning, plural forms, phrases, and result selection.",
    primaryQuestion: "Does the product communicate dictionary lookup rather than free translation?",
    deviceCondition: "Desktop Chromium proxy for French-speaking learner flow.",
    tasks: [
      {
        id: "N3-family",
        layer: "scenario_card",
        prompt: sharedScenarioPrompts.family,
        query: "tante",
        intention: "Search a French kinship lemma.",
        direction: "source_to_target",
        expectedIssueClass: "pending_human_review",
        candidateInterventionCategory: "human_review_required",
        userImpact: "Kinship terms require caution before intervention.",
      },
      {
        id: "N3-food",
        layer: "scenario_card",
        prompt: sharedScenarioPrompts.dailyLife,
        query: "fruits",
        intention: "Try a plural/category food query.",
        direction: "source_to_target",
        retryQuery: "fruit",
        retryReason: "Retry singular after plural/category attempt.",
        expectedIssueClass: "index_gap",
        candidateInterventionCategory: "source_index_supplements",
        userImpact: "Plural behavior can decide whether users recover from misses.",
      },
      {
        id: "N3-health",
        layer: "scenario_card",
        prompt: sharedScenarioPrompts.health,
        query: "malade",
        intention: "Find a health/state word from French.",
        direction: "source_to_target",
        expectedIssueClass: "pending_human_review",
        candidateInterventionCategory: "human_review_required",
        userImpact: "Health/state results need semantic validation.",
      },
      {
        id: "N3-reverse",
        layer: "scenario_card",
        prompt: sharedScenarioPrompts.reverse,
        query: "Kùn",
        intention: "Structured reverse lookup with known accented form.",
        direction: "target_to_source",
        expectedIssueClass: "probe_or_test",
        candidateInterventionCategory: "none",
        userImpact: "Known probe verifies behavior but cannot rank demand.",
      },
      {
        id: "N3-phrase",
        layer: "scenario_card",
        prompt: sharedScenarioPrompts.phrase,
        query: "je t'aime",
        intention: "Try a common social sentence.",
        direction: "source_to_target",
        expectedIssueClass: "phrase_mismatch",
        candidateInterventionCategory: "phrase_handling",
        userImpact: "Learners may expect sentence translation for social phrases.",
      },
      {
        id: "N3-offline",
        layer: "offline_check",
        prompt: sharedScenarioPrompts.offline,
        query: "travail",
        intention: "Check offline lookup for learner vocabulary.",
        direction: "source_to_target",
        expectedIssueClass: "setup_ux",
        candidateInterventionCategory: "offline_install_reliability",
        userImpact: "Offline persistence should be understandable to adult learners.",
      },
    ],
  },
  {
    id: "N4",
    location: "North America",
    userType: "Partner/spouse/friend of a Maninka speaker",
    whyThisPersonMatters: "Practical phrases, food, family, greetings, travel, mixed English/French expectations.",
    primaryQuestion: "Where does a low-context learner become confused?",
    deviceCondition: "Desktop Chromium proxy for low-context learner flow.",
    tasks: [
      {
        id: "N4-family",
        layer: "scenario_card",
        prompt: sharedScenarioPrompts.family,
        query: "famille",
        intention: "Look up broad relationship vocabulary.",
        direction: "source_to_target",
        expectedIssueClass: "interpretability",
        candidateInterventionCategory: "result_interpretability",
        userImpact: "Low-context learners may struggle with broad or multi-result entries.",
      },
      {
        id: "N4-food",
        layer: "scenario_card",
        prompt: sharedScenarioPrompts.dailyLife,
        query: "poulet",
        intention: "Search practical food vocabulary.",
        direction: "source_to_target",
        expectedIssueClass: "pending_human_review",
        candidateInterventionCategory: "human_review_required",
        userImpact: "Practical vocabulary still needs result correctness review.",
      },
      {
        id: "N4-health",
        layer: "scenario_card",
        prompt: sharedScenarioPrompts.health,
        query: "main",
        intention: "Search a basic body word.",
        direction: "source_to_target",
        expectedIssueClass: "pending_human_review",
        candidateInterventionCategory: "human_review_required",
        userImpact: "Basic terms shape trust for new learners.",
      },
      {
        id: "N4-reverse",
        layer: "scenario_card",
        prompt: sharedScenarioPrompts.reverse,
        query: "n togo",
        intention: "Try a remembered social fragment with uncertain spelling.",
        direction: "target_to_source",
        expectedIssueClass: "spelling_error",
        candidateInterventionCategory: "source_aliases",
        userImpact: "Remembered phrase fragments may not fit lemma lookup.",
      },
      {
        id: "N4-phrase",
        layer: "scenario_card",
        prompt: sharedScenarioPrompts.phrase,
        query: "how do you say thank you",
        intention: "Use English to ask for a social expression.",
        direction: "source_to_target",
        expectedIssueClass: "language_mismatch",
        candidateInterventionCategory: "product_copy_onboarding",
        userImpact: "Unsupported English/French mixing should fail safely.",
      },
      {
        id: "N4-offline",
        layer: "offline_check",
        prompt: sharedScenarioPrompts.offline,
        query: "bonjour",
        intention: "Check offline search for a greeting.",
        direction: "source_to_target",
        expectedIssueClass: "setup_ux",
        candidateInterventionCategory: "offline_install_reliability",
        userImpact: "First social searches should remain available after reopen.",
      },
    ],
  },
  {
    id: "N5",
    location: "North America",
    userType: "Community organizer, teacher, researcher, or cultural volunteer",
    whyThisPersonMatters: "Comprehensibility, discoverability, multi-result interpretation, documentation-like use.",
    primaryQuestion: "Can this be introduced to others without a maintainer beside them?",
    deviceCondition: "Desktop Chromium proxy for community introduction flow.",
    tasks: [
      {
        id: "N5-family",
        layer: "scenario_card",
        prompt: sharedScenarioPrompts.family,
        query: "parent",
        intention: "Search a broad relationship/community term.",
        direction: "source_to_target",
        expectedIssueClass: "interpretability",
        candidateInterventionCategory: "result_interpretability",
        userImpact: "Broad terms may need better result explanation.",
      },
      {
        id: "N5-community",
        layer: "scenario_card",
        prompt: sharedScenarioPrompts.dailyLife,
        query: "réunion",
        intention: "Try community or organizer vocabulary.",
        direction: "source_to_target",
        expectedIssueClass: "missing_entry",
        candidateInterventionCategory: "human_review_required",
        userImpact: "Community-use gaps should be reviewed before content work.",
      },
      {
        id: "N5-health",
        layer: "scenario_card",
        prompt: sharedScenarioPrompts.health,
        query: "hôpital",
        intention: "Search institutional health vocabulary.",
        direction: "source_to_target",
        expectedIssueClass: "missing_entry",
        candidateInterventionCategory: "human_review_required",
        userImpact: "Institutional vocabulary may matter for community support.",
      },
      {
        id: "N5-reverse",
        layer: "scenario_card",
        prompt: sharedScenarioPrompts.reverse,
        query: "Kùn",
        intention: "Check whether a known reverse lookup is explainable.",
        direction: "target_to_source",
        expectedIssueClass: "probe_or_test",
        candidateInterventionCategory: "result_interpretability",
        userImpact: "A probe can reveal explainability but not demand.",
      },
      {
        id: "N5-phrase",
        layer: "scenario_card",
        prompt: sharedScenarioPrompts.phrase,
        query: "qu'est-ce que cela veut dire",
        intention: "Ask a documentation-like learner phrase.",
        direction: "source_to_target",
        expectedIssueClass: "phrase_mismatch",
        candidateInterventionCategory: "product_copy_onboarding",
        userImpact: "Onboarding copy may need to clarify lookup boundaries.",
      },
      {
        id: "N5-offline",
        layer: "offline_check",
        prompt: sharedScenarioPrompts.offline,
        query: "langue",
        intention: "Check offline lookup for documentation-like vocabulary.",
        direction: "source_to_target",
        expectedIssueClass: "setup_ux",
        candidateInterventionCategory: "offline_install_reliability",
        userImpact: "Community introduction depends on reliable offline reopen.",
      },
    ],
  },
];
