/**
 * PRODUCT2 offline install + Credits smoke against gitignored publication candidate.
 */
import "fake-indexeddb/auto";

import { readFileSync } from "node:fs";
import { join } from "node:path";

import { afterEach, beforeEach, describe, expect, it } from "vitest";

import { projectCreditsFromManifestJson } from "./bundle_credits";
import { parseAndValidateManifestJson } from "./bundle_manifest";
import { deleteSiralexDb, getActiveBundleMeta, openSiralexDb } from "./idb/siralex_db";
import { installBundleIntoDb } from "./install/bundle_install";

const REPO_ROOT = join(import.meta.dirname, "..", "..");
const RECEIPT_PATH = join(REPO_ROOT, "data/product2/siralex_publication_readiness_v1.json");

function candidateBundleDir(): string {
  const receipt = JSON.parse(readFileSync(RECEIPT_PATH, "utf-8")) as {
    artifact_dir_name: string;
  };
  return join(REPO_ROOT, "data/product2/frozen_bundle", receipt.artifact_dir_name);
}

function fileBlob(path: string): Blob {
  return new Blob([readFileSync(path)]);
}

describe("PRODUCT2 offline publication candidate install", () => {
  beforeEach(async () => {
    await deleteSiralexDb().catch(() => undefined);
  });

  afterEach(async () => {
    await deleteSiralexDb().catch(() => undefined);
  });

  it(
    "installs frozen candidate and exposes manifest credits offline",
    async () => {
    if (!RECEIPT_PATH.endsWith(".json")) return;
    let bundleDir: string;
    try {
      bundleDir = candidateBundleDir();
      readFileSync(join(bundleDir, "bundle.manifest.json"));
    } catch {
      // Receipt generated by Python evaluate — skip when absent in CI without data workspace.
      return;
    }

    const manifestText = readFileSync(join(bundleDir, "bundle.manifest.json"), "utf-8");
    const parsed = parseAndValidateManifestJson(manifestText);
    expect(parsed.ok).toBe(true);

    const sourceCredits = projectCreditsFromManifestJson(manifestText);
    expect(sourceCredits).not.toBeNull();
    expect(sourceCredits!.sources.some((s) => s.claimed_license === "CC BY-NC-SA 4.0")).toBe(true);

    const db = await openSiralexDb();
    try {
      await installBundleIntoDb(
        db,
        parsed.manifest!,
        {
          recordsSource: fileBlob(join(bundleDir, "records.jsonl")),
          searchIndexSource: fileBlob(join(bundleDir, "search_index.jsonl")),
        },
        () => undefined,
        undefined,
        { sourceCredits: sourceCredits ?? undefined },
      );
      const active = await getActiveBundleMeta(db);
      expect(active?.source_credits?.software_license).toContain("MIT");
      expect(active?.manifest_schema_version).toBe("bundle_manifest_v2");
    } finally {
      db.close();
    }
  },
    120_000,
  );
});
